#!/usr/bin/env python3

import argparse
from pathlib import Path
from textwrap import dedent
from typing import List, Optional


def sql_literal(value: Optional[str]) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def sql_int(value: Optional[int]) -> str:
    if value is None:
        return "NULL"
    return str(value)


def write_output(content: str, output: Optional[str]) -> None:
    if output:
        path = Path(output)
        path.write_text(content, encoding="utf-8")
        print(f"[written] {path}")
        return
    print(content)


def build_header(scenario: str, db: str, params: List[str]) -> str:
    lines = [
        "-- Auto-generated by generate_mysql_case_sql.py",
        f"-- Scenario: {scenario}",
        f"-- Recommended DB: {db}",
        "-- Run in one session if you want cleanup variables to remain available.",
        "-- Parameters:",
    ]
    lines.extend(f"--   {item}" for item in params)
    return "\n".join(lines)


def render_order_status(args: argparse.Namespace) -> str:
    header = build_header(
        scenario="order-status",
        db="maitao",
        params=[
            f"order_id = {args.order_id}",
            f"target_status = {args.target_status}",
        ],
    )
    return dedent(
        f"""\
        {header}

        -- [lookup]
        SET @order_id := {sql_literal(args.order_id)};
        SET @target_status := {sql_literal(args.target_status)};
        SET @had_order := (
          SELECT COUNT(1)
          FROM orders
          WHERE order_id = @order_id
        );
        SET @orig_status := (
          SELECT status
          FROM orders
          WHERE order_id = @order_id
          LIMIT 1
        );

        SELECT
          o.order_id,
          o.order_code,
          o.user_id,
          o.activity_id,
          o.status,
          o.pay_time,
          o.verify_time,
          o.comment_status,
          o.refund_status,
          o.is_sale_data,
          o.need_settlement,
          o.update_date
        FROM orders o
        WHERE o.order_id = @order_id;

        -- [write]
        UPDATE orders
        SET status = @target_status,
            update_date = NOW()
        WHERE order_id = @order_id;

        -- [verify]
        SELECT
          o.order_id,
          o.order_code,
          o.status,
          o.pay_time,
          o.verify_time,
          o.comment_status,
          o.refund_status,
          o.update_date
        FROM orders o
        WHERE o.order_id = @order_id;

        -- [cleanup]
        UPDATE orders
        SET status = @orig_status,
            update_date = NOW()
        WHERE order_id = @order_id
          AND @had_order > 0;
        """
    ).strip()


def render_product_saleability(args: argparse.Namespace) -> str:
    activity_ref_expr = (
        sql_literal(args.activity_id)
        if args.activity_id
        else f"(SELECT activity_id FROM activity WHERE activity_code = {sql_int(args.activity_code)} LIMIT 1)"
    )
    activity_ref_label = f"activity_id = {args.activity_id}" if args.activity_id else f"activity_code = {args.activity_code}"
    header_params = [
        activity_ref_label,
        f"can_order = {args.can_order}",
    ]
    if args.activity_status is not None:
        header_params.append(f"activity_status = {args.activity_status}")
    if args.sell_status is not None:
        header_params.append(f"sell_status = {args.sell_status}")

    activity_status_write = ""
    activity_status_cleanup = ""
    if args.activity_status is not None:
        activity_status_write += dedent(
            f"""\
            UPDATE activity
            SET status = {sql_literal(args.activity_status)},
                update_date = NOW()
            WHERE activity_id = @activity_id;

            """
        )
        activity_status_cleanup += dedent(
            """\
            UPDATE activity
            SET status = @orig_activity_status,
                update_date = NOW()
            WHERE activity_id = @activity_id;

            """
        )

    sell_status_write = ""
    sell_status_cleanup = ""
    if args.sell_status is not None:
        sell_status_write += dedent(
            f"""\
            UPDATE activity
            SET sell_status = {sql_int(args.sell_status)},
                update_date = NOW()
            WHERE activity_id = @activity_id;

            """
        )
        sell_status_cleanup += dedent(
            """\
            UPDATE activity
            SET sell_status = @orig_sell_status,
                update_date = NOW()
            WHERE activity_id = @activity_id;

            """
        )

    header = build_header(
        scenario="product-saleability",
        db="maitao",
        params=header_params,
    )
    return dedent(
        f"""\
        {header}

        -- [lookup]
        SET @activity_id := {activity_ref_expr};
        SET @target_can_order := {sql_int(args.can_order)};
        SET @had_activity := (
          SELECT COUNT(1)
          FROM activity
          WHERE activity_id = @activity_id
        );
        SET @had_can_order_row := (
          SELECT COUNT(1)
          FROM act_can_order
          WHERE id = @activity_id
        );
        SET @orig_can_order := (
          SELECT can_order
          FROM act_can_order
          WHERE id = @activity_id
          LIMIT 1
        );
        SET @orig_activity_status := (
          SELECT status
          FROM activity
          WHERE activity_id = @activity_id
          LIMIT 1
        );
        SET @orig_sell_status := (
          SELECT sell_status
          FROM activity
          WHERE activity_id = @activity_id
          LIMIT 1
        );

        SELECT
          a.activity_id,
          a.activity_code,
          a.title,
          a.status,
          a.sell_status,
          a.is_waiting,
          a.onsale_time,
          a.update_date,
          aco.can_order,
          aco.create_date AS can_order_create_date,
          aco.update_date AS can_order_update_date
        FROM activity a
        LEFT JOIN act_can_order aco
          ON aco.id = a.activity_id
        WHERE a.activity_id = @activity_id;

        -- [write]
        INSERT INTO act_can_order (
          id,
          can_order,
          create_date,
          update_date
        )
        SELECT
          @activity_id,
          @target_can_order,
          NOW(),
          NOW()
        FROM DUAL
        WHERE @had_activity > 0
          AND @had_can_order_row = 0;

        UPDATE act_can_order
        SET can_order = @target_can_order,
            update_date = NOW()
        WHERE id = @activity_id
          AND @had_can_order_row > 0;

        {activity_status_write}{sell_status_write}-- [verify]
        SELECT
          a.activity_id,
          a.activity_code,
          a.title,
          a.status,
          a.sell_status,
          a.is_waiting,
          a.onsale_time,
          a.update_date,
          aco.can_order,
          aco.update_date AS can_order_update_date
        FROM activity a
        LEFT JOIN act_can_order aco
          ON aco.id = a.activity_id
        WHERE a.activity_id = @activity_id;

        -- [cleanup]
        DELETE FROM act_can_order
        WHERE id = @activity_id
          AND @had_can_order_row = 0;

        UPDATE act_can_order
        SET can_order = @orig_can_order,
            update_date = NOW()
        WHERE id = @activity_id
          AND @had_can_order_row > 0;

        {activity_status_cleanup}{sell_status_cleanup}"""
    ).strip()


def render_comment_visibility(args: argparse.Namespace) -> str:
    hide_mask = 2 if args.hide_bit == "user" else 4
    mode_comment = "user-hidden bit" if hide_mask == 2 else "system-hidden bit"
    write_sql = ""
    if args.mode == "hide":
        write_sql = dedent(
            f"""\
            UPDATE order_comment
            SET ctrl_bits = CASE
                              WHEN ctrl_bits IS NULL THEN {hide_mask}
                              ELSE ctrl_bits | {hide_mask}
                            END,
                update_date = NOW()
            WHERE order_comment_id = @order_comment_id;
            """
        ).strip()
    else:
        write_sql = dedent(
            """\
            UPDATE order_comment
            SET ctrl_bits = (
                  IFNULL(ctrl_bits, 0)
                  - IF((IFNULL(ctrl_bits, 0) & 2) > 0, 2, 0)
                  - IF((IFNULL(ctrl_bits, 0) & 4) > 0, 4, 0)
                ),
                update_date = NOW()
            WHERE order_comment_id = @order_comment_id;
            """
        ).strip()

    header = build_header(
        scenario="comment-visibility",
        db="maitao",
        params=[
            f"order_comment_id = {args.order_comment_id}",
            f"mode = {args.mode}",
            f"hide_bit = {args.hide_bit} ({mode_comment})",
        ],
    )
    return dedent(
        f"""\
        {header}

        -- [lookup]
        SET @order_comment_id := {sql_literal(args.order_comment_id)};
        SET @had_comment := (
          SELECT COUNT(1)
          FROM order_comment
          WHERE order_comment_id = @order_comment_id
        );
        SET @orig_ctrl_bits := (
          SELECT ctrl_bits
          FROM order_comment
          WHERE order_comment_id = @order_comment_id
          LIMIT 1
        );

        SELECT
          oc.order_comment_id,
          oc.order_id,
          oc.activity_id,
          oc.user_id,
          oc.ctrl_bits,
          oc.status,
          oc.comment_time,
          CASE
            WHEN oc.ctrl_bits IS NULL
              OR (oc.ctrl_bits & 2) > 0
              OR (oc.ctrl_bits & 4) > 0
            THEN 1
            ELSE 0
          END AS is_hidden
        FROM order_comment oc
        WHERE oc.order_comment_id = @order_comment_id;

        -- [write]
        {write_sql}

        -- [verify]
        SELECT
          oc.order_comment_id,
          oc.order_id,
          oc.activity_id,
          oc.ctrl_bits,
          oc.status,
          CASE
            WHEN oc.ctrl_bits IS NULL
              OR (oc.ctrl_bits & 2) > 0
              OR (oc.ctrl_bits & 4) > 0
            THEN 1
            ELSE 0
          END AS is_hidden,
          oc.update_date
        FROM order_comment oc
        WHERE oc.order_comment_id = @order_comment_id;

        -- [cleanup]
        UPDATE order_comment
        SET ctrl_bits = @orig_ctrl_bits,
            update_date = NOW()
        WHERE order_comment_id = @order_comment_id
          AND @had_comment > 0;
        """
    ).strip()


def render_channel_laxin(args: argparse.Namespace) -> str:
    if args.stu_id is not None:
        stu_expr = sql_int(args.stu_id)
        stu_label = f"stu_id = {args.stu_id}"
    else:
        stu_expr = f"(SELECT id FROM xchannel_stu WHERE name = {sql_literal(args.stu_name)} AND status = '0' ORDER BY id DESC LIMIT 1)"
        stu_label = f"stu_name = {args.stu_name}"

    header = build_header(
        scenario="channel-laxin",
        db="maitao",
        params=[
            f"unionid = {args.unionid}",
            f"external_userid = {args.external_userid}",
            f"qy_staff_id = {args.qy_staff_id}",
            stu_label,
            f"nickname = {args.nickname or ''}",
            f"create_type = {args.create_type}",
        ],
    )
    return dedent(
        f"""\
        {header}

        -- [lookup]
        SET @unionid := {sql_literal(args.unionid)};
        SET @external_userid := {sql_literal(args.external_userid)};
        SET @qy_staff_id := {sql_literal(args.qy_staff_id)};
        SET @stu_id := {stu_expr};
        SET @nickname := {sql_literal(args.nickname)};
        SET @create_type := {sql_int(args.create_type)};
        SET @existing_laxin_id := (
          SELECT xl.id
          FROM xchannel_laxin xl
          WHERE xl.wx_id = @unionid
            AND xl.external_userid = @external_userid
            AND xl.qy_staff_id = @qy_staff_id
            AND xl.stu_id = @stu_id
            AND xl.status = '0'
          ORDER BY xl.id DESC
          LIMIT 1
        );

        SELECT
          qsc.id,
          qsc.qy_staff_id,
          qsc.qy_user_id,
          qsc.unionid,
          qsc.qy_user_name,
          qsc.qy_user_remark_mobile,
          qsc.status
        FROM qy_staff_client qsc
        WHERE qsc.qy_staff_id = @qy_staff_id
          AND qsc.qy_user_id = @external_userid
          AND qsc.unionid = @unionid
        ORDER BY qsc.id DESC
        LIMIT 5;

        SELECT
          wsb.id,
          wsb.staff_id,
          wsb.qy_staff_id,
          wsb.qy_staff_name,
          wsb.status
        FROM wxwork_staff_bind wsb
        WHERE wsb.qy_staff_id = @qy_staff_id
        ORDER BY wsb.id DESC
        LIMIT 5;

        SELECT
          xs.id,
          xs.pid,
          xs.name,
          xs.department,
          xs.status
        FROM xchannel_stu xs
        WHERE xs.id = @stu_id;

        SELECT
          xl.id,
          xl.wx_id,
          xl.qy_staff_id,
          xl.external_userid,
          xl.nickname,
          xl.stu_id,
          xl.create_type,
          xl.status,
          xl.create_date
        FROM xchannel_laxin xl
        WHERE xl.id = @existing_laxin_id;

        -- [write]
        INSERT INTO xchannel_laxin (
          wx_id,
          qy_staff_id,
          external_userid,
          nickname,
          stu_id,
          create_type,
          is_sensors,
          status,
          create_date,
          update_date
        )
        SELECT
          @unionid,
          @qy_staff_id,
          @external_userid,
          NULLIF(@nickname, ''),
          @stu_id,
          @create_type,
          0,
          '0',
          NOW(),
          NOW()
        FROM DUAL
        WHERE @stu_id IS NOT NULL
          AND @existing_laxin_id IS NULL;

        SET @inserted_laxin_id := IF(
          @existing_laxin_id IS NULL AND @stu_id IS NOT NULL,
          LAST_INSERT_ID(),
          @existing_laxin_id
        );

        -- [verify]
        SELECT
          xl.id,
          xl.wx_id,
          xl.qy_staff_id,
          xl.external_userid,
          xl.nickname,
          xl.stu_id,
          xs.name AS stu_name,
          xs.pid AS stu_pid,
          xl.create_type,
          xl.is_sensors,
          xl.status,
          xl.create_date,
          xl.update_date
        FROM xchannel_laxin xl
        LEFT JOIN xchannel_stu xs
          ON xs.id = xl.stu_id
        WHERE xl.id = @inserted_laxin_id;

        -- [cleanup]
        DELETE FROM xchannel_laxin
        WHERE id = @inserted_laxin_id
          AND @existing_laxin_id IS NULL;
        """
    ).strip()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate reusable dbquery-style MySQL SQL templates for common QA data-prep scenarios."
    )
    parser.add_argument("--output", help="Write generated SQL to a file instead of stdout")

    subparsers = parser.add_subparsers(dest="scenario", required=True)

    order_status = subparsers.add_parser("order-status", help="Update one order to a target status")
    order_status.add_argument("--order-id", required=True, help="orders.order_id")
    order_status.add_argument("--target-status", required=True, help="Target orders.status value")

    product_saleability = subparsers.add_parser("product-saleability", help="Toggle product saleability via act_can_order and optional activity fields")
    product_ref = product_saleability.add_mutually_exclusive_group(required=True)
    product_ref.add_argument("--activity-id", help="activity.activity_id")
    product_ref.add_argument("--activity-code", type=int, help="activity.activity_code")
    product_saleability.add_argument("--can-order", type=int, choices=[0, 1], required=True, help="Target act_can_order.can_order")
    product_saleability.add_argument("--activity-status", choices=["1", "2", "3", "4", "5"], help="Optional target activity.status")
    product_saleability.add_argument("--sell-status", type=int, choices=[0, 1], help="Optional target activity.sell_status")

    comment_visibility = subparsers.add_parser("comment-visibility", help="Hide or show one comment by ctrl_bits")
    comment_visibility.add_argument("--order-comment-id", required=True, help="order_comment.order_comment_id")
    comment_visibility.add_argument("--mode", choices=["hide", "show"], required=True, help="Target visibility mode")
    comment_visibility.add_argument(
        "--hide-bit",
        choices=["user", "system"],
        default="system",
        help="When mode=hide, choose which hidden bit to set. Default: system",
    )

    channel_laxin = subparsers.add_parser("channel-laxin", help="Insert or verify one xchannel_laxin acquisition record")
    channel_laxin.add_argument("--unionid", required=True, help="xchannel_laxin.wx_id / qy_staff_client.unionid")
    channel_laxin.add_argument("--external-userid", required=True, help="xchannel_laxin.external_userid / qy_staff_client.qy_user_id")
    channel_laxin.add_argument("--qy-staff-id", required=True, help="xchannel_laxin.qy_staff_id / qy_staff_client.qy_staff_id")
    stu_ref = channel_laxin.add_mutually_exclusive_group(required=True)
    stu_ref.add_argument("--stu-id", type=int, help="xchannel_stu.id")
    stu_ref.add_argument("--stu-name", help="xchannel_stu.name, resolved to id in lookup SQL")
    channel_laxin.add_argument("--nickname", help="Optional external nickname")
    channel_laxin.add_argument("--create-type", type=int, choices=[0, 1], default=0, help="xchannel_laxin.create_type")

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.scenario == "order-status":
        sql = render_order_status(args)
    elif args.scenario == "product-saleability":
        sql = render_product_saleability(args)
    elif args.scenario == "comment-visibility":
        sql = render_comment_visibility(args)
    elif args.scenario == "channel-laxin":
        sql = render_channel_laxin(args)
    else:
        raise SystemExit(f"Unsupported scenario: {args.scenario}")

    write_output(sql, args.output)


if __name__ == "__main__":
    main()
